#!/bin/bash
# This file is part of Medieer.
# 
#     Medieer is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     Medieer is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <http://www.gnu.org/licenses/>.

TEMP_DIR='/tmp/m_t'

if [ -e $TEMP_DIR ]
then
	rm -rf $TEMP_DIR
fi

mkdir -p $TEMP_DIR/TV
mkdir -p $TEMP_DIR/Movies

touch "$TEMP_DIR/TV/American Dad! S6E13.mp4"
touch "$TEMP_DIR/TV/Community S1E25.mp4"
touch "$TEMP_DIR/TV/Community S2E19.mp4"
touch "$TEMP_DIR/TV/Justified S1E5.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E17.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E17.mp4"
touch "$TEMP_DIR/TV/Bob's Burgers S1E9.mp4"
touch "$TEMP_DIR/TV/Community S1E2.mp4"
touch "$TEMP_DIR/TV/Community S2E1.mp4"
touch "$TEMP_DIR/TV/Justified S1E6.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E19.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E18.mp4"
touch "$TEMP_DIR/TV/Community S1E10.mp4"
touch "$TEMP_DIR/TV/Community S1E3.mp4"
touch "$TEMP_DIR/TV/Community S2E2.mp4"
touch "$TEMP_DIR/TV/Justified S1E7.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E20.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E19.mp4"
touch "$TEMP_DIR/TV/Community S1E11.mp4"
touch "$TEMP_DIR/TV/Community S1E4.mp4"
touch "$TEMP_DIR/TV/Community S2E3.mp4"
touch "$TEMP_DIR/TV/Justified S1E8.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E21.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E1.mp4"
touch "$TEMP_DIR/TV/Community S1E12.mp4"
touch "$TEMP_DIR/TV/Community S1E5.mp4"
touch "$TEMP_DIR/TV/Community S2E4.mp4"
touch "$TEMP_DIR/TV/Justified S1E9.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E3.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E20.mp4"
touch "$TEMP_DIR/TV/Community S1E13.mp4"
touch "$TEMP_DIR/TV/Community S1E6.mp4"
touch "$TEMP_DIR/TV/Community S2E5.mp4"
touch "$TEMP_DIR/TV/Justified S2E1.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E4.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E21.mp4"
touch "$TEMP_DIR/TV/Community S1E14.mp4"
touch "$TEMP_DIR/TV/Community S1E7.mp4"
touch "$TEMP_DIR/TV/Community S2E6.mp4"
touch "$TEMP_DIR/TV/Justified S2E2.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E5.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E22.mp4"
touch "$TEMP_DIR/TV/Community S1E15.mp4"
touch "$TEMP_DIR/TV/Community S1E8.mp4"
touch "$TEMP_DIR/TV/Community S2E7.mp4"
touch "$TEMP_DIR/TV/Justified S2E3.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E6.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E3.mp4"
touch "$TEMP_DIR/TV/Community S1E16.mp4"
touch "$TEMP_DIR/TV/Community S1E9.mp4"
touch "$TEMP_DIR/TV/Community S2E8.mp4"
touch "$TEMP_DIR/TV/Justified S2E4.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E7.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E5.mp4"
touch "$TEMP_DIR/TV/Community S1E17.mp4"
touch "$TEMP_DIR/TV/Community S2E10.mp4"
touch "$TEMP_DIR/TV/Community S2E9.mp4"
touch "$TEMP_DIR/TV/Justified S2E5.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E8.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E6.mp4"
touch "$TEMP_DIR/TV/Community S1E18.mp4"
touch "$TEMP_DIR/TV/Community S2E11.mp4"
touch "$TEMP_DIR/TV/Justified S1E10.mp4"
touch "$TEMP_DIR/TV/Justified S2E6.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E9.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E7.mp4"
touch "$TEMP_DIR/TV/Community S1E19.mp4"
touch "$TEMP_DIR/TV/Community S2E12.mp4"
touch "$TEMP_DIR/TV/Justified S1E11.mp4"
touch "$TEMP_DIR/TV/Justified S2E7.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E10.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E8.mp4"
touch "$TEMP_DIR/TV/Community S1E1.mp4"
touch "$TEMP_DIR/TV/Community S2E13.mp4"
touch "$TEMP_DIR/TV/Justified S1E12.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E11.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E11.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E9.mp4"
touch "$TEMP_DIR/TV/Community S1E20.mp4"
touch "$TEMP_DIR/TV/Community S2E14.mp4"
touch "$TEMP_DIR/TV/Justified S1E13.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E12.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E12.mp4"
touch "$TEMP_DIR/TV/The Simpsons S22E16.mp4"
touch "$TEMP_DIR/TV/Community S1E21.mp4"
touch "$TEMP_DIR/TV/Community S2E15.mp4"
touch "$TEMP_DIR/TV/Justified S1E1.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E13.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E13.mp4"
touch "$TEMP_DIR/TV/The Simpsons S22E17.mp4"
touch "$TEMP_DIR/TV/Community S1E22.mp4"
touch "$TEMP_DIR/TV/Community S2E16.mp4"
touch "$TEMP_DIR/TV/Justified S1E2.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E14.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E14.mp4"
touch "$TEMP_DIR/TV/Community S1E23.mp4"
touch "$TEMP_DIR/TV/Community S2E17.mp4"
touch "$TEMP_DIR/TV/Justified S1E3.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E15.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E15.mp4"
touch "$TEMP_DIR/TV/Community S1E24.mp4"
touch "$TEMP_DIR/TV/Community S2E18.mp4"
touch "$TEMP_DIR/TV/Justified S1E4.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S2E16.mp4"
touch "$TEMP_DIR/TV/Star Wars: The Clone Wars S3E16.mp4"
touch "$TEMP_DIR/Movies/Tron.mp4"
touch "$TEMP_DIR/Movies/Star Wars: Episode V: The Empire Strikes Back.mp4"
touch "$TEMP_DIR/Movies/Star Wars: Episode III: Revenge of the Sith.mp4"
touch "$TEMP_DIR/Movies/Tron Legacy.mp4"
touch "$TEMP_DIR/Movies/Alien Resurrection.mp4"
touch "$TEMP_DIR/Movies/Super Troopers.mp4"
touch "$TEMP_DIR/Movies/Alien 3.mp4"
touch "$TEMP_DIR/Movies/Indiana Jones and the Last Crusade.mp4"
touch "$TEMP_DIR/Movies/Star Wars: Episode I: The Phantom Menace.mp4"
touch "$TEMP_DIR/Movies/The Warriors.mp4"
touch "$TEMP_DIR/Movies/Star Wars: Episode IV: A New Hope.mp4"
touch "$TEMP_DIR/Movies/Star Wars: Episode VI: Return of the Jedi.mp4"
touch "$TEMP_DIR/Movies/Alien.mp4"
touch "$TEMP_DIR/Movies/Aliens.mp4"
touch "$TEMP_DIR/Movies/WarGames.mp4"
touch "$TEMP_DIR/Movies/Indiana Jones and the Raiders of the Lost Ark.mp4"
touch "$TEMP_DIR/Movies/Indiana Jones and the Temple of Doom.mp4"
touch "$TEMP_DIR/Movies/Star Wars: Episode II: Attack of the Clones.mp4"



# for --rewind testing
# mkdir -p "$TEMP_DIR/TV/The Simpsons/Season 22/"
# mkdir -p "$TEMP_DIR/TV/Community/Season 2/"
# mkdir -p "$TEMP_DIR/TV/Community/Season 1/"
# mkdir -p "$TEMP_DIR/TV/Justified/Season 2/"
# mkdir -p "$TEMP_DIR/TV/Justified/Season 1/"
# mkdir -p "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/"
# mkdir -p "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/"
# mkdir -p "$TEMP_DIR/TV/American Dad!/Season 6/"
# mkdir -p "$TEMP_DIR/TV/Bob's Burgers/Season 1/"
# mkdir -p "$TEMP_DIR/Movies/"
# 
# touch "$TEMP_DIR/TV/The Simpsons/Season 22/Episode 17: Love Is A Many Strangled Thing.mp4"
# touch "$TEMP_DIR/TV/The Simpsons/Season 22/Episode 16: A Midsummer’s Nice Dream.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 17: Intro to Political Science.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 15: Early 21st Century Romanticism.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 7: Aerodynamics of Gender.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 14: Advanced Dungeons &amp; Dragons.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 5: Messianic Myths and Ancient Peoples.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 10: Mixology Certification.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 2: Accounting for Lawyers.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 6: Epidemiology.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 3: The Psychology of Letting Go.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 18: Custody Law and Eastern European Diplomacy.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 16: Intermediate Documentary Filmmaking.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 19: Critical Film Studies.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 13: Celebrity Pharmacology.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 4: Basic Rocket Science.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 11: Abed's Uncontrollable Christmas.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 1: Anthropology 101.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 12: Asian Population Studies.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 8: Cooperative Calligraphy.mp4"
# touch "$TEMP_DIR/TV/Community/Season 2/Episode 9: Conspiracy Theories and Interior Design.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 3: Introduction to Film.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 12: Comparative Religion.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 7: Introduction to Statistics.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 25: Pascal's Triangle Revisited.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 23: Modern Warfare.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 16: Communication Studies.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 6: Football, Feminism and You.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 17: Physical Education.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 2: Spanish 101.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 14: Interpretive Dance.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 9: Debate 109.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 11: The Politics of Human Sexuality.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 20: The Science of Illusion.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 15: Romantic Expressionism.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 8: Home Economics.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 21: Contemporary American Poultry.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 10: Environmental Science.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 22: The Art of Discourse.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 4: Social Psychology.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 19: Beginner Pottery.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 1: Pilot.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 24: English as a Second Language.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 18: Basic Genealogy.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 13: Investigative Journalism.mp4"
# touch "$TEMP_DIR/TV/Community/Season 1/Episode 5: Advanced Criminal Law.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 2/Episode 2: The Life Inside.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 2/Episode 1: The Moonshine War.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 2/Episode 6: Blaze of Glory.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 2/Episode 3: The I of the Storm.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 2/Episode 7: Save My Love.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 2/Episode 5: Cottonmouth.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 2/Episode 4: For Blood or Money.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 5: The Lord of War and Thunder.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 8: Blowback.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 4: Long in the Tooth.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 12: Fathers and Sons.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 1: Fire in the Hole.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 3: Fixer.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 13: Bulletville.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 2: Riverbrook.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 11: Veterans.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 10: The Hammer.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 6: The Collection.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 7: Blind Spot.mp4"
# touch "$TEMP_DIR/TV/Justified/Season 1/Episode 9: Hatless.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 13: Monster.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 1: Clone Cadets.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 16: Altar of Mortis.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 11: Pursuit of Peace.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 17: Ghosts of Mortis.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 9: Hunt for Ziro.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 14: Witches of the Mist.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 20: Citadel Rescue.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 12: Nightsisters.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 10: Heroes on Both Sides.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 6: The Academy.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 7: Assassin.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 19: Counter Attack.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 21: Padawan Lost.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 15: Overlords.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 5: Corruption.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 22: Wookie Hunt.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 8: Evil Plans.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 3: Supply Lines.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 3/Episode 18: The Citadel.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 4: Senate Spy.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 12: The Mandalore Plot.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 14: Duchess of Mandalore.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 11: Lightsaber Lost.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 21: R2 Come Home.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 15: Senate Murders.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 3: Children of the Force.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 6: Weapons Factory.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 7: Legacy of Terror.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 13: Voyage of Temptation.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 17: Bounty Hunters.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 16: Cat and Mouse.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 5: Landing at Point Rain.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 20: Death Trap.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 19: The Zillo Beast Strikes Back.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 8: Brain Invaders.mp4"
# touch "$TEMP_DIR/TV/Star Wars: The Clone Wars/Season 2/Episode 9: Grievous Intrigue.mp4"
# touch "$TEMP_DIR/TV/American Dad!/Season 6/Episode 13: I Am the Walrus.mp4"
# touch "$TEMP_DIR/TV/Bob's Burgers/Season 1/Episode 9: Spaghetti Western and Meatballs.mp4"
# touch "$TEMP_DIR/Movies/Tron.mp4"
# touch "$TEMP_DIR/Movies/Star Wars: Episode V: The Empire Strikes Back.mp4"
# touch "$TEMP_DIR/Movies/Star Wars: Episode III: Revenge of the Sith.mp4"
# touch "$TEMP_DIR/Movies/Tron Legacy.mp4"
# touch "$TEMP_DIR/Movies/Alien Resurrection.mp4"
# touch "$TEMP_DIR/Movies/Super Troopers.mp4"
# touch "$TEMP_DIR/Movies/Alien 3.mp4"
# touch "$TEMP_DIR/Movies/Indiana Jones and the Last Crusade.mp4"
# touch "$TEMP_DIR/Movies/Star Wars: Episode I: The Phantom Menace.mp4"
# touch "$TEMP_DIR/Movies/The Warriors.mp4"
# touch "$TEMP_DIR/Movies/Star Wars: Episode IV: A New Hope.mp4"
# touch "$TEMP_DIR/Movies/Star Wars: Episode VI: Return of the Jedi.mp4"
# touch "$TEMP_DIR/Movies/Alien.mp4"
# touch "$TEMP_DIR/Movies/Aliens.mp4"
# touch "$TEMP_DIR/Movies/WarGames.mp4"
# touch "$TEMP_DIR/Movies/Indiana Jones and the Raiders of the Lost Ark.mp4"
# touch "$TEMP_DIR/Movies/Indiana Jones and the Temple of Doom.mp4"
# touch "$TEMP_DIR/Movies/Star Wars: Episode II: Attack of the Clones.mp4"
